import pkg from 'xlsx';
const XLSX = pkg;
const { readFile } = pkg;
import fs from 'fs';

const SHIP_FILE = "SHIP-2026-03-17.xlsx";
const OUTPUT_FILE = "src/data.js";

function slugify(text) {
  if (!text) return '';
  let result = String(text).toLowerCase().trim();
  const ruMap = {
    'а': 'a', 'б': 'b', 'в': 'v', 'г': 'g', 'д': 'd', 'е': 'e', 'ё': 'yo',
    'ж': 'zh', 'з': 'z', 'и': 'i', 'й': 'y', 'к': 'k', 'л': 'l', 'м': 'm',
    'н': 'n', 'о': 'o', 'п': 'p', 'р': 'r', 'с': 's', 'т': 't', 'у': 'u',
    'ф': 'f', 'х': 'h', 'ц': 'ts', 'ч': 'ch', 'ш': 'sh', 'щ': 'sch', 'ъ': '',
    'ы': 'y', 'ь': '', 'э': 'e', 'ю': 'yu', 'я': 'ya', ' ': '-'
  };
  result = result.split('').map(char => {
    const lower = char.toLowerCase();
    return ruMap[lower] || char;
  }).join('');
  result = result.replace(/[^\w-]/g, '');
  return result.trim('-');
}

function isCategoryRow(row) {
  const keys = Object.keys(row);
  return keys.length === 1 && keys[0] === 'Наименование';
}

function parseShip() {
  if (!fs.existsSync(SHIP_FILE)) {
    console.log(`Файл ${SHIP_FILE} не найден`);
    return [];
  }
  
  const workbook = readFile(SHIP_FILE);
  const sheetName = workbook.SheetNames[0];
  const rawData = XLSX.utils.sheet_to_json(workbook.Sheets[sheetName]);
  
  const products = [];
  let currentCategory = '';
  let productId = 1;
  
  for (const row of rawData) {
    if (isCategoryRow(row)) {
      currentCategory = String(row['Наименование'] || '').trim();
      continue;
    }
    
    const name = row['Наименование'];
    const sku = row['Артикул'] || '';
    let price = row['Цена дил.'] || 0;
    let stock = row['Склад'] || 0;
    
    if (!name) continue;
    
    const title = String(name);
    let image = '';
    
    if (title.includes('SHIP')) {
      const cleanSku = String(sku).replace(/[^0-9]/g, '');
      image = `https://market-telecom.kz/files/products/${cleanSku}_1.170x220.jpg`;
    } else if (title.includes('Hyperline') || title.includes('HY')) {
      image = '';
    }
    
    products.push({
      id: productId++,
      title: title,
      articul: sku ? String(sku) : '',
      sku: sku ? String(sku) : '',
      brand: '',
      brand_name: '',
      price: parseFloat(price) || 0,
      stock: parseInt(stock) || 0,
      is_available: parseInt(stock) > 0,
      category: currentCategory ? slugify(currentCategory) : '',
      category_raw: currentCategory || '',
      image: image
    });
  }
  
  return products;
}

function generateJs(products) {
  const categoriesRaw = [...new Set(products.map(p => p.category_raw).filter(Boolean))];
  
  const categoryTree = {};
  for (const cat of categoriesRaw) {
    categoryTree[cat] = { subcategories: {} };
  }
  
  const flatCategories = Object.keys(categoryTree).map((title, i) => ({
    id: i + 1,
    title: title,
    slug: slugify(title)
  }));
  
  const brandsSet = new Set();
  for (const p of products) {
    if (p.brand_name) brandsSet.add(p.brand_name);
  }
  
  const brands = Array.from(brandsSet).sort().map((name, i) => ({
    id: i + 1,
    name: name,
    slug: slugify(name)
  }));
  
  const megaMenu = flatCategories.map((cat, i) => ({
    id: cat.id,
    title: cat.title,
    slug: cat.slug,
    image: `/${cat.title}.jpg`,
    subcategories: []
  }));
  
  const jsonString = (obj) => JSON.stringify(obj, null, 2);
  
  const jsContent = `// Auto-generated by migration script
// Data imported from SHIP-2026-03-17.xlsx

export const CONTACT_INFO = {
   phone1: "+7 (776)630-00-44",
  phone2: "+7 (747) 000-00-00",
  email: "info@servernet.kz
",
  address: "г. Петропавловск, ул. Примерная, 10111"
};

export const CATEGORIES = ${jsonString(flatCategories)};

export const BRANDS = ${jsonString(brands)};

export const MEGA_MENU_DATA = ${jsonString(megaMenu)};

export const PRODUCTS = ${jsonString(products)};
`;
  
  fs.writeFileSync(OUTPUT_FILE, jsContent, 'utf8');
  console.log(`Создан файл ${OUTPUT_FILE}`);
  console.log(`- Товаров: ${products.length}`);
  console.log(`- С изображениями: ${products.filter(p => p.image).length}`);
}

console.log('Миграция с изображениями...');
const products = parseShip();
generateJs(products);
console.log('Готово!');
