const XLSX = require('xlsx');
const fs = require('fs');

const wb = XLSX.readFile('Прайс 1.xlsx');
const ws = wb.Sheets['Каталог'];
const data = XLSX.utils.sheet_to_json(ws);

let currentCat = '';
const products = [];

data.forEach(r => {
  if (typeof r['Код'] === 'string') {
    currentCat = r['Код'];
  } else if (r['Артикул']) {
    products.push({
      category_raw: currentCat,
      code: r['Код'],
      article: r['Артикул'],
      name: r['Наименование'],
      fullName: r['Полное наименование'] || r['Наименование'],
      price: r['Цена магазин'] || 0
    });
  }
});

const mapping = {
  'Системные блоки': { category: 'kompyutery-i-komplektuyushchie', subcategory: 'sistemnye-bloki' },
  'Ноутбуки': { category: 'kompyutery-i-komplektuyushchie', subcategory: 'noutbuki-i-aksessuary' },
  'Моноблоки': { category: 'kompyutery-i-komplektuyushchie', subcategory: 'monobloki' },
  'Мини ПК': { category: 'kompyutery-i-komplektuyushchie', subcategory: 'komplektuyushchie-dlya-pk' },
  'Процессоры (CPU)': { category: 'kompyutery-i-komplektuyushchie', subcategory: 'komplektuyushchie-dlya-pk' },
  'Материнские платы (MB)': { category: 'kompyutery-i-komplektuyushchie', subcategory: 'komplektuyushchie-dlya-pk' },
  'Видеокарты (VGA)': { category: 'kompyutery-i-komplektuyushchie', subcategory: 'komplektuyushchie-dlya-pk' },
  'DDR3': { category: 'kompyutery-i-komplektuyushchie', subcategory: 'komplektuyushchie-dlya-pk' },
  'DDR4': { category: 'kompyutery-i-komplektuyushchie', subcategory: 'komplektuyushchie-dlya-pk' },
  'DDR5': { category: 'kompyutery-i-komplektuyushchie', subcategory: 'komplektuyushchie-dlya-pk' },
  'Жёсткие диски (HDD)': { category: 'kompyutery-i-komplektuyushchie', subcategory: 'komplektuyushchie-dlya-pk' },
  'Твердотельные накопители (SSD)': { category: 'kompyutery-i-komplektuyushchie', subcategory: 'komplektuyushchie-dlya-pk' },
  'Портативные диски': { category: 'kompyutery-i-komplektuyushchie', subcategory: 'komplektuyushchie-dlya-pk' },
  'Программное обеспечение': { category: 'kompyutery-i-komplektuyushchie', subcategory: 'programmnoe-obespechenie' },
  'Корпуса': { category: 'kompyutery-i-komplektuyushchie', subcategory: 'komplektuyushchie-dlya-pk' },
  'Корпуса с блоком питания': { category: 'kompyutery-i-komplektuyushchie', subcategory: 'komplektuyushchie-dlya-pk' },
  'Блоки питания': { category: 'kompyutery-i-komplektuyushchie', subcategory: 'komplektuyushchie-dlya-pk' },
  'Термопаста': { category: 'kompyutery-i-komplektuyushchie', subcategory: 'komplektuyushchie-dlya-pk' },
  'Мониторы': { category: 'kompyutery-i-komplektuyushchie', subcategory: 'monitory-i-aksessuary' },
  'Кронштейны для мониторов': { category: 'kompyutery-i-komplektuyushchie', subcategory: 'monitory-i-aksessuary' },
  'Проводные мыши': { category: 'kompyutery-i-komplektuyushchie', subcategory: 'ustroystva-vvoda-i-aksessuary' },
  'Проводные комплекты клавиатура+мышь': { category: 'kompyutery-i-komplektuyushchie', subcategory: 'ustroystva-vvoda-i-aksessuary' },
  'Беспроводные комплекты клавиатура+мышь': { category: 'kompyutery-i-komplektuyushchie', subcategory: 'ustroystva-vvoda-i-aksessuary' },
  'Беспроводные мыши': { category: 'kompyutery-i-komplektuyushchie', subcategory: 'ustroystva-vvoda-i-aksessuary' },
  'Мыши с технологией Bluetooth': { category: 'kompyutery-i-komplektuyushchie', subcategory: 'ustroystva-vvoda-i-aksessuary' },
  'Игровые мыши': { category: 'kompyutery-i-komplektuyushchie', subcategory: 'ustroystva-vvoda-i-aksessuary' },
  'Проводные клавиатуры': { category: 'kompyutery-i-komplektuyushchie', subcategory: 'ustroystva-vvoda-i-aksessuary' },
  'Беспроводные клавиатуры': { category: 'kompyutery-i-komplektuyushchie', subcategory: 'ustroystva-vvoda-i-aksessuary' },
  'Игровые клавиатуры': { category: 'kompyutery-i-komplektuyushchie', subcategory: 'ustroystva-vvoda-i-aksessuary' },
  'Коврики с тканевой поверхностью': { category: 'kompyutery-i-komplektuyushchie', subcategory: 'ustroystva-vvoda-i-aksessuary' },
  'Игровые наушники и гарнитуры': { category: 'kompyutery-i-komplektuyushchie', subcategory: 'ustroystva-vvoda-i-aksessuary' },
  'Офисные наушники и гарнитуры': { category: 'kompyutery-i-komplektuyushchie', subcategory: 'ustroystva-vvoda-i-aksessuary' },
  'Умные колонки': { category: 'kompyutery-i-komplektuyushchie', subcategory: 'ustroystva-vvoda-i-aksessuary' },
  'Графические планшеты': { category: 'kompyutery-i-komplektuyushchie', subcategory: 'ustroystva-vvoda-i-aksessuary' },
  'Карты флеш памяти': { category: 'kompyutery-i-komplektuyushchie', subcategory: 'komplektuyushchie-dlya-pk' },
  'Телевизоры': { category: 'kompyutery-i-komplektuyushchie', subcategory: 'monitory-i-aksessuary' },
  'Цифровые телевизионные приёмники': { category: 'kompyutery-i-komplektuyushchie', subcategory: 'monitory-i-aksessuary' },
  'Кронштейны для ТВ': { category: 'kompyutery-i-komplektuyushchie', subcategory: 'monitory-i-aksessuary' },
  'Пульты для ТВ': { category: 'kompyutery-i-komplektuyushchie', subcategory: 'monitory-i-aksessuary' },
  'Сумки и чехлы': { category: 'kompyutery-i-komplektuyushchie', subcategory: 'noutbuki-i-aksessuary' },
  'Электронные книги': { category: 'kompyutery-i-komplektuyushchie', subcategory: 'komplektuyushchie-dlya-pk' },
  'Очки виртуальной реальности': { category: 'kompyutery-i-komplektuyushchie', subcategory: 'komplektuyushchie-dlya-pk' },
  'Линейно-интерактивные': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'aktivnoe-setevoe' },
  'Напольные': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'aktivnoe-setevoe' },
  'Стоечные 19"': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'telekommunikacionnye-shkafy' },
  'Интеллектуальное управление электропитанием': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'aktivnoe-setevoe' },
  'Трёхфазные ': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'aktivnoe-setevoe' },
  'Модульные': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'aktivnoe-setevoe' },
  'Батарейные блоки': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'aktivnoe-setevoe' },
  'Шкафы для батарей, аксессуары для ИБП': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'aktivnoe-setevoe' },
  'Однофазные': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'aktivnoe-setevoe' },
  'Трёхфазные': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'aktivnoe-setevoe' },
  'Поликристалические солнечные панели': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'aktivnoe-setevoe' },
  'Аксессуары': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'telekommunikacionnye-shkafy' },
  'Из 12В,24В,48В в 220В': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'aktivnoe-setevoe' },
  'Гелевые (GEL)': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'aktivnoe-setevoe' },
  'Свинцово-кислотные (AGM)': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'aktivnoe-setevoe' },
  'Готовые решения': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'servery' },
  'Серверные платформы': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'servery' },
  'Серверы': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'servery' },
  'ПО и лицензии': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'servery' },
  'Материнские платы': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'servery' },
  'Intel': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'sistemy-hraneniya-dannyh' },
  'AMD': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'sistemy-hraneniya-dannyh' },
  'ECC UDIMM': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'sistemy-hraneniya-dannyh' },
  '2.5" (SFF)': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'sistemy-hraneniya-dannyh' },
  'M.2': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'sistemy-hraneniya-dannyh' },
  'SAS': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'sistemy-hraneniya-dannyh' },
  'Сетевые адаптеры': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'aktivnoe-setevoe' },
  'Системы хранения данных': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'sistemy-hraneniya-dannyh' },
  'HDD и SSD': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'sistemy-hraneniya-dannyh' },
  'Неуправляемые SOHO': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'aktivnoe-setevoe' },
  'Управляемые SOHO': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'aktivnoe-setevoe' },
  'Неуправляемые стоечные': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'aktivnoe-setevoe' },
  'Управляемые стоечные': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'aktivnoe-setevoe' },
  'Неуправляемые SOHO PoE': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'aktivnoe-setevoe' },
  'Неуправляемые стоечные PoE': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'aktivnoe-setevoe' },
  'Управляемые SOHO PoE': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'aktivnoe-setevoe' },
  'Управляемые стоечные PoE': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'aktivnoe-setevoe' },
  'Неуправляемые индустриальные': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'aktivnoe-setevoe' },
  'Управляемые индустриальные': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'aktivnoe-setevoe' },
  'SOHO маршрутизаторы': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'aktivnoe-setevoe' },
  'Корпоративные маршрутизаторы': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'aktivnoe-setevoe' },
  'GSM LTE Модемы Роутеры': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'aktivnoe-setevoe' },
  'Mesh системы': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'aktivnoe-setevoe' },
  'Корпоративный Wi-Fi': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'aktivnoe-setevoe' },
  'Wi-Fi радио мосты': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'aktivnoe-setevoe' },
  'Репитеры/усилители Wi-Fi': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'aktivnoe-setevoe' },
  'IP Телефоны': { category: 'ip-telefony', subcategory: 'ip-telefony' },
  'IP АТС и шлюзы': { category: 'ip-telefony', subcategory: 'ip-telefony' },
  'Модемы': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'aktivnoe-setevoe' },
  'PoE адаптеры': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'aktivnoe-setevoe' },
  'USB': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'aktivnoe-setevoe' },
  'Оборудование xPON': { category: 'kabelnye-sistemy', subcategory: 'komponenty-dlya-optovolokonnoj-seti' },
  'Оптические модули 1G SFP': { category: 'kabelnye-sistemy', subcategory: 'komponenty-dlya-optovolokonnoj-seti' },
  'Оптические модули 10G SFP+': { category: 'kabelnye-sistemy', subcategory: 'komponenty-dlya-optovolokonnoj-seti' },
  'Оптические модули 25G SFP28': { category: 'kabelnye-sistemy', subcategory: 'komponenty-dlya-optovolokonnoj-seti' },
  'Оптические модули 40G QSFP+': { category: 'kabelnye-sistemy', subcategory: 'komponenty-dlya-optovolokonnoj-seti' },
  'Оптические модули 100G QSFP28': { category: 'kabelnye-sistemy', subcategory: 'komponenty-dlya-optovolokonnoj-seti' },
  'Медиаконвертеры': { category: 'kabelnye-sistemy', subcategory: 'komponenty-dlya-optovolokonnoj-seti' },
  'Антенны': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'aktivnoe-setevoe' },
  'Источники питания': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'telekommunikacionnye-shkafy' },
  'Сетевые камеры': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-videonablyudeniya' },
  'Шкафы напольные, серверные': { category: 'kabelnye-sistemy', subcategory: 'passivnoe-setevoe' },
  'Шкафы навесные, настенные': { category: 'kabelnye-sistemy', subcategory: 'passivnoe-setevoe' },
  'Аксессуары для шкафов и стоек': { category: 'kabelnye-sistemy', subcategory: 'passivnoe-setevoe' },
  'Кабели витая пара': { category: 'kabelnye-sistemy', subcategory: 'passivnoe-setevoe' },
  'Сетевые патч корды': { category: 'kabelnye-sistemy', subcategory: 'passivnoe-setevoe' },
  'Коннекторы': { category: 'kabelnye-sistemy', subcategory: 'passivnoe-setevoe' },
  'Колпачки (буты)': { category: 'kabelnye-sistemy', subcategory: 'passivnoe-setevoe' },
  'Модули': { category: 'kabelnye-sistemy', subcategory: 'passivnoe-setevoe' },
  'Розетки настенные': { category: 'kabelnye-sistemy', subcategory: 'passivnoe-setevoe' },
  'Лицевые панели': { category: 'kabelnye-sistemy', subcategory: 'passivnoe-setevoe' },
  'Соединительные панели и муфты': { category: 'kabelnye-sistemy', subcategory: 'passivnoe-setevoe' },
  'В грунт': { category: 'kabelnye-sistemy', subcategory: 'komponenty-dlya-optovolokonnoj-seti' },
  'В кабельную канализацию': { category: 'kabelnye-sistemy', subcategory: 'komponenty-dlya-optovolokonnoj-seti' },
  'В трубы': { category: 'kabelnye-sistemy', subcategory: 'komponenty-dlya-optovolokonnoj-seti' },
  'Подвесные самонесущие': { category: 'kabelnye-sistemy', subcategory: 'komponenty-dlya-optovolokonnoj-seti' },
  'Городские подвесные с вынесенным металлическим элементом': { category: 'kabelnye-sistemy', subcategory: 'komponenty-dlya-optovolokonnoj-seti' },
  'Подвесные диэлектрические  ': { category: 'kabelnye-sistemy', subcategory: 'komponenty-dlya-optovolokonnoj-seti' },
  'Подвесные FTTH': { category: 'kabelnye-sistemy', subcategory: 'komponenty-dlya-optovolokonnoj-seti' },
  'Локальные': { category: 'kabelnye-sistemy', subcategory: 'komponenty-dlya-optovolokonnoj-seti' },
  'Оптические муфты': { category: 'kabelnye-sistemy', subcategory: 'komponenty-dlya-optovolokonnoj-seti' },
  'Сварочные аппараты и рефлектометры для оптоволокна': { category: 'kabelnye-sistemy', subcategory: 'komponenty-dlya-optovolokonnoj-seti' },
  'Арматура для оптоволоконной продукции': { category: 'kabelnye-sistemy', subcategory: 'komponenty-dlya-optovolokonnoj-seti' },
  'Оптические полки и кроссы': { category: 'kabelnye-sistemy', subcategory: 'komponenty-dlya-optovolokonnoj-seti' },
  'Оптоволоконные патч корды 2.0 Simplex Одномод': { category: 'kabelnye-sistemy', subcategory: 'komponenty-dlya-optovolokonnoj-seti' },
  'Оптоволоконные патч корды 2.0 Duplex Одномод': { category: 'kabelnye-sistemy', subcategory: 'komponenty-dlya-optovolokonnoj-seti' },
  'Оптоволоконные патч корды 3.0 Simplex Одномод': { category: 'kabelnye-sistemy', subcategory: 'komponenty-dlya-optovolokonnoj-seti' },
  'Оптоволоконные патч корды 3.0 Simplex Многомод': { category: 'kabelnye-sistemy', subcategory: 'komponenty-dlya-optovolokonnoj-seti' },
  'Оптоволоконные патч корды 3.0 Duplex Одномод': { category: 'kabelnye-sistemy', subcategory: 'komponenty-dlya-optovolokonnoj-seti' },
  'Оптоволоконные патч корды 3.0 Duplex Многомод': { category: 'kabelnye-sistemy', subcategory: 'komponenty-dlya-optovolokonnoj-seti' },
  'Абонентские дроп патч корды (FTTH)': { category: 'kabelnye-sistemy', subcategory: 'komponenty-dlya-optovolokonnoj-seti' },
  'Оптоволоконные пигтейлы Одномод': { category: 'kabelnye-sistemy', subcategory: 'komponenty-dlya-optovolokonnoj-seti' },
  'Оптоволоконные пигтейлы Многомод': { category: 'kabelnye-sistemy', subcategory: 'komponenty-dlya-optovolokonnoj-seti' },
  'Оптоволоконные адаптеры и розетки': { category: 'kabelnye-sistemy', subcategory: 'komponenty-dlya-optovolokonnoj-seti' },
  'Оптоволоконные сплиттеры': { category: 'kabelnye-sistemy', subcategory: 'komponenty-dlya-optovolokonnoj-seti' },
  '2 мегапиксельные IP видеокамеры': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-videonablyudeniya' },
  '4 мегапиксельные IP видеокамеры': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-videonablyudeniya' },
  '5 мегапиксельные IP видеокамеры': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-videonablyudeniya' },
  '8 мегапиксельные IP видеокамеры': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-videonablyudeniya' },
  'Видеокамеры специального назначения': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-videonablyudeniya' },
  '4 канальные видеорегистраторы': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-videonablyudeniya' },
  '8 канальные видеорегистраторы': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-videonablyudeniya' },
  '16 канальные видеорегистраторы': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-videonablyudeniya' },
  '32 канальные видеорегистраторы': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-videonablyudeniya' },
  'Многоканальные видеорегистраторы': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-videonablyudeniya' },
  '2 мегапиксельные Wi-Fi видеокамеры': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-videonablyudeniya' },
  '3 мегапиксельные Wi-Fi видеокамеры': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-videonablyudeniya' },
  '4 мегапиксельные Wi-Fi видеокамеры': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-videonablyudeniya' },
  '5 мегапиксельные Wi-Fi видеокамеры': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-videonablyudeniya' },
  '8 мегапиксельные Wi-Fi видеокамеры': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-videonablyudeniya' },
  '2 мегапиксельные HD видеокамеры': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-videonablyudeniya' },
  '5 и более мегапиксельные HD видеокамеры': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-videonablyudeniya' },
  '8 мегапиксельные HD видеокамеры': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-videonablyudeniya' },
  '4 канальные HD видеорегистраторы': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-videonablyudeniya' },
  '8 канальные HD видеорегистраторы': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-videonablyudeniya' },
  '16 канальные HD видеорегистраторы': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-videonablyudeniya' },
  '32 канальные HD видеорегистраторы': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-videonablyudeniya' },
  'GSM сигнализаторы': { category: 'sistemy-bezopasnosti', subcategory: 'ohrannye-i-pozharnye-sistemy' },
  'Брелки радиоканальные': { category: 'sistemy-bezopasnosti', subcategory: 'ohrannye-i-pozharnye-sistemy' },
  'Приемно-контрольные приборы': { category: 'sistemy-bezopasnosti', subcategory: 'ohrannye-i-pozharnye-sistemy' },
  'Извещатели пожарные': { category: 'sistemy-bezopasnosti', subcategory: 'ohrannye-i-pozharnye-sistemy' },
  'Извещатели охранные': { category: 'sistemy-bezopasnosti', subcategory: 'ohrannye-i-pozharnye-sistemy' },
  'Оповещатели свето-звуковые': { category: 'sistemy-bezopasnosti', subcategory: 'ohrannye-i-pozharnye-sistemy' },
  'Комплекты': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-kontrolya-dostupa' },
  'Вызывные панели': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-kontrolya-dostupa' },
  'Мониторы видеодомофонии': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-kontrolya-dostupa' },
  'Одноабонентные панели': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-kontrolya-dostupa' },
  'Многоабонентные панели': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-kontrolya-dostupa' },
  'Мониторы видеодомофонии и преобразователи': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-kontrolya-dostupa' },
  'Контроллеры со считывателем': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-kontrolya-dostupa' },
  'Контроллеры без считывателя': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-kontrolya-dostupa' },
  'Считыватели': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-kontrolya-dostupa' },
  'Идентификаторы': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-kontrolya-dostupa' },
  'Турникеты и металлоискатели': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-kontrolya-dostupa' },
  'Шлагбаумы': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-kontrolya-dostupa' },
  'Замки и доводчики': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-kontrolya-dostupa' },
  'Кнопки выхода и гибкие переходы': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-kontrolya-dostupa' },
  'Кронштейны': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-videonablyudeniya' },
  'Монтажные коробки для видеонаблюдения': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-videonablyudeniya' },
  'Монтажные коробки для видеодомофонии и контроллеров': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-kontrolya-dostupa' },
  'Клавиатуры управления и приборы': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-videonablyudeniya' },
  'ИК прожекторы': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-videonablyudeniya' },
  'Резервируемые блоки питания': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-videonablyudeniya' },
  'Нерезервируемые блоки питания': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-videonablyudeniya' },
  'Адаптеры': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-videonablyudeniya' },
  'Коннекторы и переходники': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-videonablyudeniya' },
  'Кабельно-проводниковая продукция': { category: 'kabelnye-sistemy', subcategory: 'passivnoe-setevoe' },
  'Зеркальные': { category: 'kommercheskaya-vizualizaciya', subcategory: 'professionalnye-paneli' },
  'Беззеркальные': { category: 'kommercheskaya-vizualizaciya', subcategory: 'professionalnye-paneli' },
  'Компактные': { category: 'kommercheskaya-vizualizaciya', subcategory: 'professionalnye-paneli' },
  'Профессиональные видеокамеры': { category: 'kommercheskaya-vizualizaciya', subcategory: 'professionalnye-paneli' },
  'Экшн-камеры': { category: 'kommercheskaya-vizualizaciya', subcategory: 'interaktivnye-paneli' },
  'Фотопринтеры и бумага': { category: 'kommercheskaya-vizualizaciya', subcategory: 'aksessuary-vizualizaciya' },
  'Аксессуары для экшн-камер': { category: 'kommercheskaya-vizualizaciya', subcategory: 'aksessuary-vizualizaciya' },
  'Объективы для фото и видеокамер': { category: 'kommercheskaya-vizualizaciya', subcategory: 'aksessuary-vizualizaciya' },
  'Вспышки и освещение': { category: 'kommercheskaya-vizualizaciya', subcategory: 'aksessuary-vizualizaciya' },
  'Аккумуляторы, зарядные устройства': { category: 'kommercheskaya-vizualizaciya', subcategory: 'aksessuary-vizualizaciya' },
  'Софтбоксы': { category: 'kommercheskaya-vizualizaciya', subcategory: 'aksessuary-vizualizaciya' },
  'Штативы для фото и видео техники': { category: 'kommercheskaya-vizualizaciya', subcategory: 'aksessuary-vizualizaciya' },
  'Интерактивные панели': { category: 'kommercheskaya-vizualizaciya', subcategory: 'interaktivnye-paneli' },
  'Оборудование для видеоконференций': { category: 'kommercheskaya-vizualizaciya', subcategory: 'interaktivnye-paneli' },
  'Проекторы': { category: 'kommercheskaya-vizualizaciya', subcategory: 'interaktivnye-paneli' },
  'Кронштейны для проекторов': { category: 'kommercheskaya-vizualizaciya', subcategory: 'kronshtejny-dlya-video-sten' },
  'Монохромные лазерные принтеры А4': { category: 'ofisnoe-oborudovanie', subcategory: 'ofisnoe-oborudovanie' },
  'Цветные лазерные принтеры А3': { category: 'ofisnoe-oborudovanie', subcategory: 'ofisnoe-oborudovanie' },
  'Цветные лазерные принтеры А4': { category: 'ofisnoe-oborudovanie', subcategory: 'ofisnoe-oborudovanie' },
  'Монохромные лазерные МФУ А3': { category: 'ofisnoe-oborudovanie', subcategory: 'ofisnoe-oborudovanie' },
  'Монохромные лазерные МФУ А4': { category: 'ofisnoe-oborudovanie', subcategory: 'ofisnoe-oborudovanie' },
  'Цветные лазерные МФУ А3': { category: 'ofisnoe-oborudovanie', subcategory: 'ofisnoe-oborudovanie' },
  'Цветные лазерные МФУ А4': { category: 'ofisnoe-oborudovanie', subcategory: 'ofisnoe-oborudovanie' },
  'Цветные струйные принтеры А4': { category: 'ofisnoe-oborudovanie', subcategory: 'ofisnoe-oborudovanie' },
  'Цветные струйные принтеры А3': { category: 'ofisnoe-oborudovanie', subcategory: 'ofisnoe-oborudovanie' },
  'Монохромные струйные МФУ А4': { category: 'ofisnoe-oborudovanie', subcategory: 'ofisnoe-oborudovanie' },
  'Цветные струйные МФУ А4': { category: 'ofisnoe-oborudovanie', subcategory: 'ofisnoe-oborudovanie' },
  'Плоттеры': { category: 'ofisnoe-oborudovanie', subcategory: 'ofisnoe-oborudovanie' },
  'Широкоформатные сканеры': { category: 'ofisnoe-oborudovanie', subcategory: 'ofisnoe-oborudovanie' },
  'Сканеры': { category: 'ofisnoe-oborudovanie', subcategory: 'ofisnoe-oborudovanie' },
  'Ламинаторы': { category: 'ofisnoe-oborudovanie', subcategory: 'ofisnoe-oborudovanie' },
  'Фольгираторы': { category: 'ofisnoe-oborudovanie', subcategory: 'ofisnoe-oborudovanie' },
  'Переплётные машины': { category: 'ofisnoe-oborudovanie', subcategory: 'ofisnoe-oborudovanie' },
  'Резаки': { category: 'ofisnoe-oborudovanie', subcategory: 'ofisnoe-oborudovanie' },
  'Уничтожители бумаги (Шредеры)': { category: 'ofisnoe-oborudovanie', subcategory: 'ofisnoe-oborudovanie' },
  'Системы "Умный дом"': { category: 'sistemy-bezopasnosti', subcategory: 'sistemy-videonablyudeniya' },
  'Канальные кондиционеры Inverter': { category: 'demonstracionnoe-oborudovanie', subcategory: 'demonstracionnoe-oborudovanie' },
  'Мульти-сплит-системы TCL': { category: 'demonstracionnoe-oborudovanie', subcategory: 'demonstracionnoe-oborudovanie' },
  'Напольно-потолочные кондиционеры Inverter': { category: 'demonstracionnoe-oborudovanie', subcategory: 'demonstracionnoe-oborudovanie' },
  'Настенные кондиционеры': { category: 'demonstracionnoe-oborudovanie', subcategory: 'demonstracionnoe-oborudovanie' },
  'Настенные кондиционеры Inverter': { category: 'demonstracionnoe-oborudovanie', subcategory: 'demonstracionnoe-oborudovanie' },
  'Колонные кондиционеры': { category: 'demonstracionnoe-oborudovanie', subcategory: 'demonstracionnoe-oborudovanie' },
  'Напольные вентиляторы': { category: 'demonstracionnoe-oborudovanie', subcategory: 'demonstracionnoe-oborudovanie' },
  'Настольные вентиляторы': { category: 'demonstracionnoe-oborudovanie', subcategory: 'demonstracionnoe-oborudovanie' },
  'Конвекторные обогреватели': { category: 'demonstracionnoe-oborudovanie', subcategory: 'demonstracionnoe-oborudovanie' },
  'Масляные обогреватели': { category: 'demonstracionnoe-oborudovanie', subcategory: 'demonstracionnoe-oborudovanie' },
  'Увлажнители воздуха': { category: 'demonstracionnoe-oborudovanie', subcategory: 'demonstracionnoe-oborudovanie' },
  'Очистители воздуха': { category: 'demonstracionnoe-oborudovanie', subcategory: 'demonstracionnoe-oborudovanie' },
  'Кулеры для воды': { category: 'demonstracionnoe-oborudovanie', subcategory: 'demonstracionnoe-oborudovanie' },
  'Силовой кабель и провод': { category: 'kabelnye-sistemy', subcategory: 'passivnoe-setevoe' },
  'Сетевые фильтры': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'aktivnoe-setevoe' },
  'Щиты металлические': { category: 'setevoe-i-servernoe-oborudovanie', subcategory: 'telekommunikacionnye-shkafy' },
};

const mapped = products.map(p => {
  const m = mapping[p.category_raw];
  return m ? { ...p, category: m.category, subcategory: m.subcategory } : { ...p, category: 'other', subcategory: 'other' };
});

const counts = {};
mapped.forEach(p => { counts[p.category] = (counts[p.category] || 0) + 1; });
console.log('Category counts:', JSON.stringify(counts, null, 2));
console.log('Total products:', mapped.length);

const unmapped = mapped.filter(p => p.category === 'other');
if (unmapped.length > 0) {
  console.log('Unmapped categories:', [...new Set(unmapped.map(p => p.category_raw))]);
}

fs.writeFileSync('new-products.json', JSON.stringify(mapped, null, 2));
console.log('Saved to new-products.json');