// Auto-generated by migration script
// Data imported from Прайс 1.xlsx + SHIP-2026-03-17.xlsx

export const CONTACT_INFO = {
  phone1: "+7 (776)630-00-44",
  phone2: "+7 (776)630-00-44",
  email: "info@servernet.kz",
  address: "Казахстан, г. Петропавловск, ул. Чкалова, 49"
};

export const HEADER_CATEGORIES = [
  { 
    id: 1, 
    title: "Видеонаблюдение", 
    slug: "videonablyudenie",
    image: "/videonablyudenie.jpg",
    subcategories: [
      { slug: "analogovye-videokamery", name: "Аналоговые видеокамеры" },
      { slug: "ip-videokamery", name: "IP видеокамеры" },
      { slug: "gibridnye-videoregistratory", name: "Гибридные видеорегистраторы" },
      { slug: "ip-videoregistratory", name: "IP видеорегистраторы" }
    ]
  },
  { 
    id: 2, 
    title: "Домофония", 
    slug: "domofoniya",
    image: "/domofoniya.jpg",
    subcategories: [
      { slug: "komplekty", name: "Комплекты" },
      { slug: "vyzyvnye-paneli", name: "Вызывные панели" },
      { slug: "monitory", name: "Мониторы" },
      { slug: "zamki-i-dovodnye", name: "Замки и доводчики" },
      { slug: "klavishi-i-perekhody", name: "Клавиши и переходы" }
    ]
  },
  { 
    id: 3, 
    title: "Системы контроля доступа", 
    slug: "sistemy-kontrolya-dostupa",
    image: "/sistemy-kontrolya-dostupa.jpg",
    subcategories: [
      { slug: "kontrollery", name: "Контроллеры" },
      { slug: "schityvateli", name: "Считыватели" },
      { slug: "turnikety", name: "Турникеты" },
      { slug: "shlagbaummy", name: "Шлагбаумы" }
    ]
  },
  { 
    id: 4, 
    title: "IP-телефоны", 
    slug: "ip-telefony",
    image: "/ip-telefony.jpg",
    subcategories: [
      { slug: "nastolnye-telefony", name: "Настольные телефоны" },
      { slug: "besprovodnye-telefony", name: "Беспроводные телефоны" },
      { slug: "otelnye-telefony", name: "Отельные телефоны" },
      { slug: "videotelefonы", name: "Видео-телефоны" },
      { slug: "konferenciya", name: "Конференция" },
      { slug: "mini-ats", name: "Мини АТС" },
      { slug: "fxo-shpuli", name: "FXO шпули" },
      { slug: "fxs-shpuli", name: "FXS шпули" },
      { slug: "gsm-shpuli", name: "GSM шпули" }
    ]
  },
  { 
    id: 5, 
    title: "Пожарная сигнализация", 
    slug: "pozharnaya-signalizaciya",
    image: "/pozharnaya-signalizaciya.jpg",
    subcategories: [
      { slug: "priemno-kontolnye-pribory", name: "Премо-контрольные приборы" },
      { slug: "izveshchateli-pozharnyе", name: "Извещатели пожарные" },
      { slug: "izveshchateli-ohrannye", name: "Извещатели охранные" },
      { slug: "opoveschateli-sveto-zvukovye", name: "Оповещатели свето-звуковые" }
    ]
  },
  { 
    id: 6, 
    title: "Сетевое оборудование", 
    slug: "setevoe-oborudovanie",
    image: "/setevoe-oborudovanie.jpg",
    subcategories: [
      { slug: "marshrutizatory", name: "Маршрутизаторы" },
      { slug: "kommutatory-lan", name: "Коммутаторы LAN" },
      { slug: "kommutatory-poe", name: "Коммутаторы PoE" },
      { slug: "mediakonvertory", name: "Медиаконвертеры" },
      { slug: "sfp-moduli", name: "SFP-модули" },
      { slug: "inzhektory-poe", name: "Инжекторы PoE" }
    ]
  },
  { 
    id: 7, 
    title: "Пассивное сетевое", 
    slug: "passivnoe-setevoe",
    image: "/passivnoe-setevoe.jpg",
    subcategories: [
      { slug: "vitaya-para", name: "Витая пара" },
      { slug: "patchkordy", name: "Патчкорды" },
      { slug: "rozetki", name: "Розетки" },
      { slug: "konnektory", name: "Коннекторы" },
      { slug: "moduli", name: "Модули" },
      { slug: "kabelno-provodnaya-produkciya", name: "Кабельно-проводниковая продукция" }
    ]
  },
  { 
    id: 8, 
    title: "Источники бесперебойного питания", 
    slug: "istochniki-besperebojnogo-pitaniya",
    image: "/istochniki-besperebojnogo-pitaniya.jpg",
    subcategories: [
      { slug: "smart-ups", name: "Smart UPS" },
      { slug: "online-ups", name: "Online UPS" },
      { slug: "trekhfaznye-ups", name: "Трёхфазные UPS" },
      { slug: "batareynye-bloki", name: "Батарейные блоки" },
      { slug: "akkumulyatory-dlya-ibp", name: "Аккумуляторы для ИБП" },
      { slug: "shkafi-dlya-akkumulyatorov", name: "Шкафы для аккумуляторов" }
    ]
  },
  { 
    id: 9, 
    title: "Серверные шкафы", 
    slug: "servernye-shkafi",
    image: "/servernye-shkafi.jpg",
    subcategories: [
      { slug: "nastolnye-shkafi", name: "Настольные" },
      { slug: "napolnye-shkafi", name: "Напольные" },
      { slug: "komplektuyushchie-k-shkafam", name: "Комплектующие к шкафам" },
      { slug: "klimaticheskie-shkafi", name: "Климатические шкафы" }
    ]
  },
  { 
    id: 10, 
    title: "Гарнитура", 
    slug: "garnitura",
    image: "/garnitura.jpg",
    subcategories: [
      { slug: "provodnaya", name: "Проводная" },
      { slug: "besprovodnaya", name: "Беспроводная" },
      { slug: "mesh-sistemy", name: "MESH-системы" }
    ]
  },
  { 
    id: 11, 
    title: "WiFi оборудование", 
    slug: "wifi-oborudovanie",
    image: "/wifi-oborudovanie.jpg",
    subcategories: [
      { slug: "wifi-routery", name: "WiFi роутеры" },
      { slug: "tochki-dostupa-wifi", name: "Точки доступа WiFi" },
      { slug: "wifi-mosty", name: "WiFi мосты" },
      { slug: "mesh-sistemy", name: "MESH-системы" }
    ]
  },
  { 
    id: 12, 
    title: "Радиооборудование", 
    slug: "radiooborudovanie",
    image: "/radiooborudovanie.jpg",
    subcategories: [
      { slug: "radiostancii", name: "Радиостанции" },
      { slug: "antenny", name: "Антенны" },
      { slug: "povtoriteli-svyazi", name: "Повторители связи" },
      { slug: "matchi", name: "Матчи" }
    ]
  },
  { 
    id: 13, 
    title: "Оптоволоконная продукция", 
    slug: "optovolokonaya-produkciya",
    image: "/optovolokonaya-produkciya.jpg",
    subcategories: [
      { slug: "optovolokonnyy-kabel", name: "Оптоволоконный кабель" },
      { slug: "opticheskie-patch-kordy", name: "Оптические патч корды" },
      { slug: "adaptry-i-rozetki", name: "Адаптеры и розетки" }
    ]
  }
];

export const CATEGORIES = HEADER_CATEGORIES;

const categoryMap = {
  // Video Surveillance
  "Аналоговые видеокамеры": { category: "videonablyudenie", subcategory: "analogovye-videokamery" },
  "IP видеокамеры": { category: "videonablyudenie", subcategory: "ip-videokamery" },
  "Гибридные видеорегистраторы": { category: "videonablyudenie", subcategory: "gibridnye-videoregistratory" },
  "IP видеорегистраторы": { category: "videonablyudenie", subcategory: "ip-videoregistratory" },
  "2 мегапиксельные IP видеокамеры": { category: "videonablyudenie", subcategory: "ip-videokamery" },
  "4 мегапиксельные IP видеокамеры": { category: "videonablyudenie", subcategory: "ip-videokamery" },
  "5 мегапиксельные IP видеокамеры": { category: "videonablyudenie", subcategory: "ip-videokamery" },
  "8 мегапиксельные IP видеокамеры": { category: "videonablyudenie", subcategory: "ip-videokamery" },
  "4 канальные видеорегистраторы": { category: "videonablyudenie", subcategory: "ip-videoregistratory" },
  "8 канальные видеорегистраторы": { category: "videonablyudenie", subcategory: "ip-videoregistratory" },
  "16 канальные видеорегистраторы": { category: "videonablyudenie", subcategory: "ip-videoregistratory" },
  "32 канальные видеорегистраторы": { category: "videonablyudenie", subcategory: "ip-videoregistratory" },
  
  // Intercom
  "Комплекты": { category: "domofoniya", subcategory: "komplekty" },
  "Вызывные панели": { category: "domofoniya", subcategory: "vyzyvnye-paneli" },
  "Мониторы": { category: "domofoniya", subcategory: "monitory" },
  "Замки и доводчики": { category: "domofoniya", subcategory: "zamki-i-dovodnye" },
  "Клавиши и переходы": { category: "domofoniya", subcategory: "klavishi-i-perekhody" },
  
  // Access Control
  "Контроллеры": { category: "sistemy-kontrolya-dostupa", subcategory: "kontrollery" },
  "Считыватели": { category: "sistemy-kontrolya-dostupa", subcategory: "schityvateli" },
  "Турникеты": { category: "sistemy-kontrolya-dostupa", subcategory: "turnikety" },
  "Шлагбаумы": { category: "sistemy-kontrolya-dostupa", subcategory: "shlagbaummy" },
  
  // IP Phones
  "Настольные телефоны": { category: "ip-telefony", subcategory: "nastolnye-telefony" },
  "Беспроводные телефоны": { category: "ip-telefony", subcategory: "besprovodnye-telefony" },
  "Отельные телефоны": { category: "ip-telefony", subcategory: "otelnye-telefony" },
  "Видео-телефоны": { category: "ip-telefony", subcategory: "videotelefonы" },
  "Конференция": { category: "ip-telefony", subcategory: "konferenciya" },
  "Мини АТС": { category: "ip-telefony", subcategory: "mini-ats" },
  "FXO шпули": { category: "ip-telefony", subcategory: "fxo-shpuli" },
  "FXS шпули": { category: "ip-telefony", subcategory: "fxs-shpuli" },
  "GSM шпули": { category: "ip-telefony", subcategory: "gsm-shpuli" },
  "IP Телефоны": { category: "ip-telefony", subcategory: "nastolnye-telefony" },
  "IP АТС и шлюзы": { category: "ip-telefony", subcategory: "mini-ats" },
  
  // Fire Alarm
  "Премо-контрольные приборы": { category: "pozharnaya-signalizaciya", subcategory: "priemno-kontolnye-pribory" },
  "Извещатели пожарные": { category: "pozharnaya-signalizaciya", subcategory: "izveshchateli-pozharnyе" },
  "Извещатели охранные": { category: "pozharnaya-signalizaciya", subcategory: "izveshchateli-ohrannye" },
  "Оповещатели свето-звуковые": { category: "pozharnaya-signalizaciya", subcategory: "opoveschateli-sveto-zvukovye" },
  "GSM сигнализаторы": { category: "pozharnaya-signalizaciya", subcategory: "izveshchateli-ohrannye" },
  "Приемно-контрольные приборы": { category: "pozharnaya-signalizaciya", subcategory: "priemno-kontolnye-pribory" },
  
  // Network Equipment
  "Маршрутизаторы": { category: "setevoe-oborudovanie", subcategory: "marshrutizatory" },
  "Коммутаторы LAN": { category: "setevoe-oborudovanie", subcategory: "kommutatory-lan" },
  "Коммутаторы PoE": { category: "setevoe-oborudovanie", subcategory: "kommutatory-poe" },
  "Медиаконвертеры": { category: "setevoe-oborudovanie", subcategory: "mediakonvertory" },
  "SFP-модули": { category: "setevoe-oborudovanie", subcategory: "sfp-moduli" },
  "Инжекторы PoE": { category: "setevoe-oborudovanie", subcategory: "inzhektory-poe" },
  "Неуправляемые SOHO": { category: "setevoe-oborudovanie", subcategory: "kommutatory-lan" },
  "Управляемые SOHO": { category: "setevoe-oborudovanie", subcategory: "kommutatory-lan" },
  "SOHO маршрутизаторы": { category: "setevoe-oborudovanie", subcategory: "marshrutizatory" },
  "Корпоративные маршрутизаторы": { category: "setevoe-oborudovanie", subcategory: "marshrutizatory" },
  "GSM LTE Модемы Роутеры": { category: "setevoe-oborudovanie", subcategory: "marshrutizatory" },
  "Mesh системы": { category: "setevoe-oborudovanie", subcategory: "kommutatory-lan" },
  
  // Passive Network
  "Витая пара": { category: "passivnoe-setevoe", subcategory: "vitaya-para" },
  "Патчкорды": { category: "passivnoe-setevoe", subcategory: "patchkordy" },
  "Розетки": { category: "passivnoe-setevoe", subcategory: "rozetki" },
  "Коннекторы": { category: "passivnoe-setevoe", subcategory: "konnektory" },
  "Модули": { category: "passivnoe-setevoe", subcategory: "moduli" },
  "Кабельно-проводниковая продукция": { category: "passivnoe-setevoe", subcategory: "kabelno-provodnaya-produkciya" },
  "Кабели витая пара": { category: "passivnoe-setevoe", subcategory: "vitaya-para" },
  "Сетевые патч корды": { category: "passivnoe-setevoe", subcategory: "patchkordy" },
  "Колпачки (буты)": { category: "passivnoe-setevoe", subcategory: "konnektory" },
  "Соединительные панели и муфты": { category: "passivnoe-setevoe", subcategory: "rozetki" },
  "Лицевые панели": { category: "passivnoe-setevoe", subcategory: "rozetki" },
  "Розетки настенные": { category: "passivnoe-setevoe", subcategory: "rozetki" },
  "Силовой кабель и провод": { category: "passivnoe-setevoe", subcategory: "kabelno-provodnaya-produkciya" },
  "Патч-Панели": { category: "passivnoe-setevoe", subcategory: "rozetki" },
  
  // UPS
  "Smart UPS": { category: "istochniki-besperebojnogo-pitaniya", subcategory: "smart-ups" },
  "Online UPS": { category: "istochniki-besperebojnogo-pitaniya", subcategory: "online-ups" },
  "Трёхфазные UPS": { category: "istochniki-besperebojnogo-pitaniya", subcategory: "trekhfaznye-ups" },
  "Батарейные блоки": { category: "istochniki-besperebojnogo-pitaniya", subcategory: "batareynye-bloki" },
  "Аккумуляторы для ИБП": { category: "istochniki-besperebojnogo-pitaniya", subcategory: "akkumulyatory-dlya-ibp" },
  "Шкафы для аккумуляторов": { category: "istochniki-besperebojnogo-pitaniya", subcategory: "shkafi-dlya-akkumulyatorov" },
  
  // Server Cabinets
  "Настольные": { category: "servernye-shkafi", subcategory: "nastolnye-shkafi" },
  "Напольные": { category: "servernye-shkafi", subcategory: "napolnye-shkafi" },
  "Комплектующие к шкафам": { category: "servernye-shkafi", subcategory: "komplektuyushchie-k-shkafam" },
  "Климатические шкафы": { category: "servernye-shkafi", subcategory: "klimaticheskie-shkafi" },
  "Шкафы напольные, серверные": { category: "servernye-shkafi", subcategory: "napolnye-shkafi" },
  "Шкафы навесные, настенные": { category: "servernye-shkafi", subcategory: "nastolnye-shkafi" },
  "Аксессуары для шкафов и стоек": { category: "servernye-shkafi", subcategory: "komplektuyushchie-k-shkafam" },
  
  // Headsets
  "Проводная": { category: "garnitura", subcategory: "provodnaya" },
  "Беспроводная": { category: "garnitura", subcategory: "besprovodnaya" },
  "MESH-системы": { category: "garnitura", subcategory: "mesh-sistemy" },
  "Проводные мыши": { category: "garnitura", subcategory: "provodnaya" },
  "Беспроводные мыши": { category: "garnitura", subcategory: "besprovodnaya" },
  "Гарнитуры и микрофоны": { category: "garnitura", subcategory: "provodnaya" },
  "Офисные наушники и гарнитуры": { category: "garnitura", subcategory: "provodnaya" },
  
  // WiFi Equipment
  "WiFi роутеры": { category: "wifi-oborudovanie", subcategory: "wifi-routery" },
  "Точки доступа WiFi": { category: "wifi-oborudovanie", subcategory: "tochki-dostupa-wifi" },
  "WiFi мосты": { category: "wifi-oborudovanie", subcategory: "wifi-mosty" },
  "Корпоративный Wi-Fi": { category: "wifi-oborudovanie", subcategory: "tochki-dostupa-wifi" },
  "Wi-Fi радио мосты": { category: "wifi-oborudovanie", subcategory: "wifi-mosty" },
  "Репитеры/усилители Wi-Fi": { category: "wifi-oborudovanie", subcategory: "tochki-dostupa-wifi" },
  
  // Radio Equipment
  "Радиостанции": { category: "radiooborudovanie", subcategory: "radiostancii" },
  "Антенны": { category: "radiooborudovanie", subcategory: "antenny" },
  "Повторители связи": { category: "radiooborudovanie", subcategory: "povtoriteli-svyazi" },
  "Матчи": { category: "radiooborudovanie", subcategory: "matchi" },
  "Подавители связи": { category: "radiooborudovanie", subcategory: "antenny" },
  "Мачты": { category: "radiooborudovanie", subcategory: "antenny" },
  "Аккумуляторы": { category: "radiooborudovanie", subcategory: "radiostancii" },
  "Зарядные устройства": { category: "radiooborudovanie", subcategory: "radiostancii" },
  "Ретрансляторы": { category: "radiooborudovanie", subcategory: "povtoriteli-svyazi" },
  "Дуплексеры": { category: "radiooborudovanie", subcategory: "matchi" },
  "Инверторы": { category: "radiooborudovanie", subcategory: "radiostancii" },
  "Преобразователи": { category: "radiooborudovanie", subcategory: "radiostancii" },
  "Репитеры": { category: "radiooborudovanie", subcategory: "povtoriteli-svyazi" },
  "GPS-трекеры": { category: "radiooborudovanie", subcategory: "radiostancii" },
  "Кронштейны": { category: "radiooborudovanie", subcategory: "antenny" },
  "Кабели": { category: "radiooborudovanie", subcategory: "antenny" },
  "Громкоговорители": { category: "radiooborudovanie", subcategory: "radiostancii" },
  "Сплиттеры": { category: "radiooborudovanie", subcategory: "matchi" },
  "Усилители": { category: "radiooborudovanie", subcategory: "radiostancii" },
  "Блоки питания": { category: "radiooborudovanie", subcategory: "radiostancii" },
  "Программаторы": { category: "radiooborudovanie", subcategory: "radiostancii" },
  "5.4. GSM-маяки": { category: "radiooborudovanie", subcategory: "povtoriteli-svyazi" },
  "7.4. Источники питания": { category: "radiooborudovanie", subcategory: "radiostancii" },
  "Радиосинхронизаторы": { category: "radiooborudovanie", subcategory: "povtoriteli-svyazi" },
  
  // Fiber Optics
  "Оптоволоконный кабель": { category: "optovolokonaya-produkciya", subcategory: "optovolokonnyy-kabel" },
  "Оптические патч корды": { category: "optovolokonaya-produkciya", subcategory: "opticheskie-patch-kordy" },
  "Адаптеры и розетки": { category: "optovolokonaya-produkciya", subcategory: "adaptry-i-rozetki" },
  "Оптические модули 1G SFP": { category: "optovolokonaya-produkciya", subcategory: "optovolokonnyy-kabel" },
  "Оптические модули 10G SFP+": { category: "optovolokonaya-produkciya", subcategory: "optovolokonnyy-kabel" },
  "Оптические модули 25G SFP28": { category: "optovolokonaya-produkciya", subcategory: "optovolokonnyy-kabel" },
  "Оптические модули 40G QSFP+": { category: "optovolokonaya-produkciya", subcategory: "optovolokonnyy-kabel" },
  "Оптические модули 100G QSFP28": { category: "optovolokonaya-produkciya", subcategory: "optovolokonnyy-kabel" },
  "Оптические муфты": { category: "optovolokonaya-produkciya", subcategory: "adaptry-i-rozetki" },
  "Оптические полки и кроссы": { category: "optovolokonaya-produkciya", subcategory: "adaptry-i-rozetki" },
  "Оптоволоконные адаптеры и розетки": { category: "optovolokonaya-produkciya", subcategory: "adaptry-i-rozetki" },
  "Оптоволоконные сплиттеры": { category: "optovolokonaya-produkciya", subcategory: "adaptry-i-rozetki" },
  "Оборудование xPON": { category: "optovolokonaya-produkciya", subcategory: "adaptry-i-rozetki" },
  "РОЗЕТКИ АБОНЕНТСКИЕ": { category: "optovolokonaya-produkciya", subcategory: "adaptry-i-rozetki" }
};

export const CATEGORY_MAP = categoryMap;

// Import products from new-products.json (Прайс 1.xlsx)
import newProductsData from './new-products.json' with { type: "json" };
import price1ProductsData from './price1-products.json' with { type: "json" };
import price2ProductsData from './price2-products.json' with { type: "json" };
import price3ProductsData from './price3-products.json' with { type: "json" };
import imageMapData from './image-map.json' with { type: "json" };

const RAW_PRODUCTS = [...newProductsData, ...price1ProductsData, ...price2ProductsData, ...price3ProductsData];

const BLANK_PHOTO = 'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="400" height="300"><rect fill="%23f1f5f9" width="400" height="300"/><text x="200" y="150" text-anchor="middle" dominant-baseline="middle" fill="%2364748b" font-family="system-ui,sans-serif" font-size="16">Фото скоро будет</text></svg>';

function getProductImage(code, article) {
  if (!code && !article) return BLANK_PHOTO;
  
  // Try code first
  if (code) {
    const codeStr = String(code);
    const images = imageMapData[codeStr] || imageMapData[codeStr.padStart(5, '0')];
    if (images && images.length > 0) {
      return `/${images[0]}`;
    }
  }
  
  // Try article (lowercase)
  if (article) {
    const articleStr = String(article).toLowerCase();
    const images = imageMapData[articleStr];
    if (images && images.length > 0) {
      return `/${images[0]}`;
    }
  }
  
  return BLANK_PHOTO;
}

export const PRODUCTS = RAW_PRODUCTS.map((p, index) => {
  const mapping = categoryMap[p.category_raw];
  const cat = mapping ? mapping.category : p.category;
  const subcat = mapping ? mapping.subcategory : p.subcategory;
  
  return {
    ...p,
    id: `prod-${p.code || index}-${index}`,
    title: p.name || p.fullName || 'Без названия',
    articul: p.article || String(p.code),
    sku: p.article || String(p.code),
    brand: "",
    brand_name: "",
    price: Number(p.price) || 0,
    stock: 10,
    is_available: true,
    category: cat || 'other',
    category_raw: p.category_raw,
    image: getProductImage(p.code, p.article),
    description: p.fullName || p.name || "",
    subcategory: subcat || 'other'
  };
});

export const BRANDS = [];

export const MEGA_MENU_DATA = [
  {
    id: 1,
    title: "Видеонаблюдение",
    slug: "videonablyudenie",
    subcategories: [
      { slug: "analogovye-videokamery", name: "Аналоговые видеокамеры" },
      { slug: "ip-videokamery", name: "IP видеокамеры" },
      { slug: "gibridnye-videoregistratory", name: "Гибридные видеорегистраторы" },
      { slug: "ip-videoregistratory", name: "IP видеорегистраторы" }
    ]
  },
  {
    id: 2,
    title: "Домофония",
    slug: "domofoniya",
    subcategories: [
      { slug: "komplekty", name: "Комплекты" },
      { slug: "vyzyvnye-paneli", name: "Вызывные панели" },
      { slug: "monitory", name: "Мониторы" },
      { slug: "zamki-i-dovodnye", name: "Замки и доводчики" },
      { slug: "klavishi-i-perekhody", name: "Клавиши и переходы" }
    ]
  },
  {
    id: 3,
    title: "Системы контроля доступа",
    slug: "sistemy-kontrolya-dostupa",
    subcategories: [
      { slug: "kontrollery", name: "Контроллеры" },
      { slug: "schityvateli", name: "Считыватели" },
      { slug: "turnikety", name: "Турникеты" },
      { slug: "shlagbaummy", name: "Шлагбаумы" }
    ]
  },
  {
    id: 4,
    title: "IP-телефоны",
    slug: "ip-telefony",
    subcategories: [
      { slug: "nastolnye-telefony", name: "Настольные телефоны" },
      { slug: "besprovodnye-telefony", name: "Беспроводные телефоны" },
      { slug: "otelnye-telefony", name: "Отельные телефоны" },
      { slug: "videotelefonы", name: "Видео-телефоны" },
      { slug: "konferenciya", name: "Конференция" },
      { slug: "mini-ats", name: "Мини АТС" },
      { slug: "fxo-shpuli", name: "FXO шпули" },
      { slug: "fxs-shpuli", name: "FXS шпули" },
      { slug: "gsm-shpuli", name: "GSM шпули" }
    ]
  },
  {
    id: 5,
    title: "Пожарная сигнализация",
    slug: "pozharnaya-signalizaciya",
    subcategories: [
      { slug: "priemno-kontolnye-pribory", name: "Премо-контрольные приборы" },
      { slug: "izveshchateli-pozharnyе", name: "Извещатели пожарные" },
      { slug: "izveshchateli-ohrannye", name: "Извещатели охранные" },
      { slug: "opoveschateli-sveto-zvukovye", name: "Оповещатели свето-звуковые" }
    ]
  },
  {
    id: 6,
    title: "Сетевое оборудование",
    slug: "setevoe-oborudovanie",
    subcategories: [
      { slug: "marshrutizatory", name: "Маршрутизаторы" },
      { slug: "kommutatory-lan", name: "Коммутаторы LAN" },
      { slug: "kommutatory-poe", name: "Коммутаторы PoE" },
      { slug: "mediakonvertory", name: "Медиаконвертеры" },
      { slug: "sfp-moduli", name: "SFP-модули" },
      { slug: "inzhektory-poe", name: "Инжекторы PoE" }
    ]
  },
  {
    id: 7,
    title: "Пассивное сетевое",
    slug: "passivnoe-setevoe",
    subcategories: [
      { slug: "vitaya-para", name: "Витая пара" },
      { slug: "patchkordy", name: "Патчкорды" },
      { slug: "rozetki", name: "Розетки" },
      { slug: "konnektory", name: "Коннекторы" },
      { slug: "moduli", name: "Модули" },
      { slug: "kabelno-provodnaya-produkciya", name: "Кабельно-проводниковая продукция" }
    ]
  },
  {
    id: 8,
    title: "Источники бесперебойного питания",
    slug: "istochniki-besperebojnogo-pitaniya",
    subcategories: [
      { slug: "smart-ups", name: "Smart UPS" },
      { slug: "online-ups", name: "Online UPS" },
      { slug: "trekhfaznye-ups", name: "Трёхфазные UPS" },
      { slug: "batareynye-bloki", name: "Батарейные блоки" },
      { slug: "akkumulyatory-dlya-ibp", name: "Аккумуляторы для ИБП" },
      { slug: "shkafi-dlya-akkumulyatorov", name: "Шкафы для аккумуляторов" }
    ]
  },
  {
    id: 9,
    title: "Серверные шкафы",
    slug: "servernye-shkafi",
    subcategories: [
      { slug: "nastolnye-shkafi", name: "Настольные" },
      { slug: "napolnye-shkafi", name: "Напольные" },
      { slug: "komplektuyushchie-k-shkafam", name: "Комплектующие к шкафам" },
      { slug: "klimaticheskie-shkafi", name: "Климатические шкафы" }
    ]
  },
  {
    id: 10,
    title: "Гарнитура",
    slug: "garnitura",
    subcategories: [
      { slug: "provodnaya", name: "Проводная" },
      { slug: "besprovodnaya", name: "Беспроводная" },
      { slug: "mesh-sistemy", name: "MESH-системы" }
    ]
  },
  {
    id: 11,
    title: "WiFi оборудование",
    slug: "wifi-oborudovanie",
    subcategories: [
      { slug: "wifi-routery", name: "WiFi роутеры" },
      { slug: "tochki-dostupa-wifi", name: "Точки доступа WiFi" },
      { slug: "wifi-mosty", name: "WiFi мосты" },
      { slug: "mesh-sistemy", name: "MESH-системы" }
    ]
  },
  {
    id: 12,
    title: "Радиооборудование",
    slug: "radiooborudovanie",
    subcategories: [
      { slug: "radiostancii", name: "Радиостанции" },
      { slug: "antenny", name: "Антенны" },
      { slug: "povtoriteli-svyazi", name: "Повторители связи" },
      { slug: "matchi", name: "Матчи" }
    ]
  },
  {
    id: 13,
    title: "Оптоволоконная продукция",
    slug: "optovolokonaya-produkciya",
    subcategories: [
      { slug: "optovolokonnyy-kabel", name: "Оптоволоконный кабель" },
      { slug: "opticheskie-patch-kordy", name: "Оптические патч корды" },
      { slug: "adaptry-i-rozetki", name: "Адаптеры и розетки" }
    ]
  }
];

// Map menu category/subcategory slugs → actual product category/subcategory values
export const MENU_SLUG_TO_PRODUCT_MAP = {
  // Top-level categories
  "videonablyudenie": { category: "videonablyudenie" },
  "domofoniya": { category: "domofoniya" },
  "sistemy-kontrolya-dostupa": { category: "sistemy-kontrolya-dostupa" },
  "ip-telefony": { category: "ip-telefony" },
  "pozharnaya-signalizaciya": { category: "pozharnaya-signalizaciya" },
  "setevoe-oborudovanie": { category: "setevoe-oborudovanie" },
  "passivnoe-setevoe": { category: "passivnoe-setevoe" },
  "istochniki-besperebojnogo-pitaniya": { category: "istochniki-besperebojnogo-pitaniya" },
  "servernye-shkafi": { category: "servernye-shkafi" },
  "garnitura": { category: "garnitura" },
  "wifi-oborudovanie": { category: "wifi-oborudovanie" },
  "radiooborudovanie": { category: "radiooborudovanie" },
  "optovolokonaya-produkciya": { category: "optovolokonaya-produkciya" },
  
  // Video Surveillance subcategories
  "analogovye-videokamery": { category: "videonablyudenie", subcategory: "analogovye-videokamery" },
  "ip-videokamery": { category: "videonablyudenie", subcategory: "ip-videokamery" },
  "gibridnye-videoregistratory": { category: "videonablyudenie", subcategory: "gibridnye-videoregistratory" },
  "ip-videoregistratory": { category: "videonablyudenie", subcategory: "ip-videoregistratory" },
  
  // Intercom subcategories
  "komplekty": { category: "domofoniya", subcategory: "komplekty" },
  "vyzyvnye-paneli": { category: "domofoniya", subcategory: "vyzyvnye-paneli" },
  "monitory": { category: "domofoniya", subcategory: "monitory" },
  "zamki-i-dovodnye": { category: "domofoniya", subcategory: "zamki-i-dovodnye" },
  "klavishi-i-perekhody": { category: "domofoniya", subcategory: "klavishi-i-perekhody" },
  
  // Access Control subcategories
  "kontrollery": { category: "sistemy-kontrolya-dostupa", subcategory: "kontrollery" },
  "schityvateli": { category: "sistemy-kontrolya-dostupa", subcategory: "schityvateli" },
  "turnikety": { category: "sistemy-kontrolya-dostupa", subcategory: "turnikety" },
  "shlagbaummy": { category: "sistemy-kontrolya-dostupa", subcategory: "shlagbaummy" },
  
  // IP Phones subcategories
  "nastolnye-telefony": { category: "ip-telefony", subcategory: "nastolnye-telefony" },
  "besprovodnye-telefony": { category: "ip-telefony", subcategory: "besprovodnye-telefony" },
  "otelnye-telefony": { category: "ip-telefony", subcategory: "otelnye-telefony" },
  "videotelefonы": { category: "ip-telefony", subcategory: "videotelefonы" },
  "konferenciya": { category: "ip-telefony", subcategory: "konferenciya" },
  "mini-ats": { category: "ip-telefony", subcategory: "mini-ats" },
  "fxo-shpuli": { category: "ip-telefony", subcategory: "fxo-shpuli" },
  "fxs-shpuli": { category: "ip-telefony", subcategory: "fxs-shpuli" },
  "gsm-shpuli": { category: "ip-telefony", subcategory: "gsm-shpuli" },
  
  // Fire Alarm subcategories
  "priemno-kontolnye-pribory": { category: "pozharnaya-signalizaciya", subcategory: "priemno-kontolnye-pribory" },
  "izveshchateli-pozharnyе": { category: "pozharnaya-signalizaciya", subcategory: "izveshchateli-pozharnyе" },
  "izveshchateli-ohrannye": { category: "pozharnaya-signalizaciya", subcategory: "izveshchateli-ohrannye" },
  "opoveschateli-sveto-zvukovye": { category: "pozharnaya-signalizaciya", subcategory: "opoveschateli-sveto-zvukovye" },
  
  // Network Equipment subcategories
  "marshrutizatory": { category: "setevoe-oborudovanie", subcategory: "marshrutizatory" },
  "kommutatory-lan": { category: "setevoe-oborudovanie", subcategory: "kommutatory-lan" },
  "kommutatory-poe": { category: "setevoe-oborudovanie", subcategory: "kommutatory-poe" },
  "mediakonvertory": { category: "setevoe-oborudovanie", subcategory: "mediakonvertory" },
  "sfp-moduli": { category: "setevoe-oborudovanie", subcategory: "sfp-moduli" },
  "inzhektory-poe": { category: "setevoe-oborudovanie", subcategory: "inzhektory-poe" },
  
  // Passive Network subcategories
  "vitaya-para": { category: "passivnoe-setevoe", subcategory: "vitaya-para" },
  "patchkordy": { category: "passivnoe-setevoe", subcategory: "patchkordy" },
  "rozetki": { category: "passivnoe-setevoe", subcategory: "rozetki" },
  "konnektory": { category: "passivnoe-setevoe", subcategory: "konnektory" },
  "moduli": { category: "passivnoe-setevoe", subcategory: "moduli" },
  "kabelno-provodnaya-produkciya": { category: "passivnoe-setevoe", subcategory: "kabelno-provodnaya-produkciya" },
  
  // UPS subcategories
  "smart-ups": { category: "istochniki-besperebojnogo-pitaniya", subcategory: "smart-ups" },
  "online-ups": { category: "istochniki-besperebojnogo-pitaniya", subcategory: "online-ups" },
  "trekhfaznye-ups": { category: "istochniki-besperebojnogo-pitaniya", subcategory: "trekhfaznye-ups" },
  "batareynye-bloki": { category: "istochniki-besperebojnogo-pitaniya", subcategory: "batareynye-bloki" },
  "akkumulyatory-dlya-ibp": { category: "istochniki-besperebojnogo-pitaniya", subcategory: "akkumulyatory-dlya-ibp" },
  "shkafi-dlya-akkumulyatorov": { category: "istochniki-besperebojnogo-pitaniya", subcategory: "shkafi-dlya-akkumulyatorov" },
  
  // Server Cabinets subcategories
  "nastolnye-shkafi": { category: "servernye-shkafi", subcategory: "nastolnye-shkafi" },
  "napolnye-shkafi": { category: "servernye-shkafi", subcategory: "napolnye-shkafi" },
  "komplektuyushchie-k-shkafam": { category: "servernye-shkafi", subcategory: "komplektuyushchie-k-shkafam" },
  "klimaticheskie-shkafi": { category: "servernye-shkafi", subcategory: "klimaticheskie-shkafi" },
  
  // Headsets subcategories
  "provodnaya": { category: "garnitura", subcategory: "provodnaya" },
  "besprovodnaya": { category: "garnitura", subcategory: "besprovodnaya" },
  "mesh-sistemy": { category: "garnitura", subcategory: "mesh-sistemy" },
  
  // WiFi Equipment subcategories
  "wifi-routery": { category: "wifi-oborudovanie", subcategory: "wifi-routery" },
  "tochki-dostupa-wifi": { category: "wifi-oborudovanie", subcategory: "tochki-dostupa-wifi" },
  "wifi-mosty": { category: "wifi-oborudovanie", subcategory: "wifi-mosty" },
  
  // Radio Equipment subcategories
  "radiostancii": { category: "radiooborudovanie", subcategory: "radiostancii" },
  "antenny": { category: "radiooborudovanie", subcategory: "antenny" },
  "povtoriteli-svyazi": { category: "radiooborudovanie", subcategory: "povtoriteli-svyazi" },
  "matchi": { category: "radiooborudovanie", subcategory: "matchi" },
  
  // Fiber Optics subcategories
  "optovolokonnyy-kabel": { category: "optovolokonaya-produkciya", subcategory: "optovolokonnyy-kabel" },
  "opticheskie-patch-kordy": { category: "optovolokonaya-produkciya", subcategory: "opticheskie-patch-kordy" },
  "adaptry-i-rozetki": { category: "optovolokonaya-produkciya", subcategory: "adaptry-i-rozetki" }
};